version: "3"

services:
    
    mysql01:
        image: robinong79/mysql_repl:5.7
        ports:
            - "3307:3306"
        networks:
            - mysqlcluster
        environment:
            - MYSQL_ROOT_PASSWORD=root1234
            - SERVER_ID=1
            - BIND_ADDRESS=0.0.0.0
        volumes:
            - mysql01:/var/lib/mysql
            - mysql01:/etc/mysql/conf.d
            - mysql01:/docker-entrypoint-initdb.d
            - mysql01:/var/log/mysql
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 60s
            restart_policy:
                condition: none
                max_attempts: 5
            placement:
                constraints: [node.role == manager]
                
volumes:
  mysql01:

networks:
    mysqlcluster:
        external: true

