version: "3"

services:
   
    mysqlfailover:
        image: robinong79/mysqlfailover:1.6.4
        networks:
            - mysqlcluster
        environment:
            - MYSQL_ROOT_PASSWORD=root1234
            - MASTER=mysql01
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 60s
            restart_policy:
                condition: none
                max_attempts: 5

    mysqlrouter:
        image: robinong79/mysqlrouter:2.0.4
        ports:
            - "3309:3306"            
        networks:
            - mysqlcluster
        environment:
            - MLOGGER_LEVEL=ERROR
            - MYSQLROUTER_BINDPORT=3306
            - DESTINATIONS=mysql01:3306,mysql02:3306
        volumes:
            - log:/var/log/mysqlrouter
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 60s
            restart_policy:
                condition: none
                max_attempts: 5
            placement:
                constraints: [node.labels.mysql != false]
volumes:
    log:
networks:
    mysqlcluster:
        external: true

