version: "3"

services:
    
    mysql02:
        image: robinong79/mysql_repl:5.7 
        ports:
            - "3308:3306"
        networks:
            - mysqlcluster
        environment:
            - MYSQL_ROOT_PASSWORD=root1234
            - SERVER_ID=2
            - BIND_ADDRESS=0.0.0.0
            - AUTO_INIT_MASTER_IP=mysql01
        volumes:
            - mysql02-lib:/var/lib/mysql
            - mysql02-conf:/etc/mysql/conf.d
            - mysql02-initdb:/var/log/mysql
            - mysql02-log:/docker-entrypoint-initdb.d
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 60s
            restart_policy:
                condition: on-failure
                max_attempts: 5
            placement:
                constraints: [node.hostname == proxy]
                
volumes:
  mysql02-lib:
  mysql02-conf:
  mysql02-initdb:
  mysql02-log:

networks:
    mysqlcluster:
        external: true
